package chess

import (
	"bufio"
	"os"
	"strconv"
	"strings"
	"testing"
)

// Chess960 verification.
//
// The suite in testdata is Andrew Grant's, generated by taking all 960 starting
// arrangements, playing eight random plies into each with Stockfish, and
// recording exact node counts to depth 6. Eight plies is deliberate: it puts
// castling genuinely in play in most positions, which is where Chess960 differs
// from classical chess and where a generalized generator can go wrong.
//
// The suite matters because Chess960 breaks assumptions classical castling code
// takes for granted — the king does not start on e1, rooks do not start on the
// corners, and king and rook paths overlap, up to the king not moving at all.

type epdCase struct {
	fen    string
	counts []uint64 // counts[i] is perft at depth i+1
	line   int
}

func loadEPD(t *testing.T, path string) []epdCase {
	t.Helper()

	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	var cases []epdCase
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	for lineNo := 1; scanner.Scan(); lineNo++ {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Format: <FEN> ;D1 <n> ;D2 <n> ...
		parts := strings.Split(line, ";")
		c := epdCase{fen: strings.TrimSpace(parts[0]), line: lineNo}

		for _, p := range parts[1:] {
			fields := strings.Fields(strings.TrimSpace(p))
			if len(fields) != 2 || !strings.HasPrefix(fields[0], "D") {
				t.Fatalf("%s:%d: malformed depth clause %q", path, lineNo, p)
			}
			depth, err := strconv.Atoi(strings.TrimPrefix(fields[0], "D"))
			if err != nil {
				t.Fatalf("%s:%d: bad depth %q", path, lineNo, fields[0])
			}
			n, err := strconv.ParseUint(fields[1], 10, 64)
			if err != nil {
				t.Fatalf("%s:%d: bad node count %q", path, lineNo, fields[1])
			}
			if depth != len(c.counts)+1 {
				t.Fatalf("%s:%d: depths out of order at D%d", path, lineNo, depth)
			}
			c.counts = append(c.counts, n)
		}
		cases = append(cases, c)
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return cases
}

// TestChess960Perft runs the full 960-position suite. Depths are limited by the
// same node budget as the classical suite unless -perft-full is given, so the
// default run still covers every one of the 960 arrangements — breadth matters
// more here than depth, since each arrangement exercises a different castling
// geometry.
func TestChess960Perft(t *testing.T) {
	cases := loadEPD(t, "testdata/chess960_perft.epd")
	if len(cases) != 960 {
		t.Fatalf("loaded %d positions, want all 960 arrangements", len(cases))
	}

	// Depth 6 across all 960 arrangements is on the order of 200 billion
	// nodes, which is not a test but an overnight job. Every arrangement is
	// verified to depth 5 always; -perft-full adds depth 6 for a fixed sample.
	// The sample is reported rather than applied silently, so the output never
	// implies more coverage than was run.
	const deepSampleStride = 40
	deepSampled := 0

	var positions, deepest int
	var nodes uint64

	for caseIdx, tc := range cases {
		p, err := ParseFEN(tc.fen)
		if err != nil {
			t.Fatalf("line %d: ParseFEN(%q): %v", tc.line, tc.fen, err)
		}
		// Shredder notation is the only signal a FEN carries, so a position
		// that has already lost both castling rights cannot be recognized as
		// Chess960 — and need not be, since the flag only governs how castling
		// is written and there is none left.
		if p.CastlingRights() != NoCastling && !p.IsChess960() {
			t.Fatalf("line %d: position with castling rights not detected as Chess960: %q", tc.line, tc.fen)
		}

		for i, want := range tc.counts {
			depth := i + 1
			if want > maxPerftNodes {
				if !*perftFull {
					break
				}
				if caseIdx%deepSampleStride != 0 {
					break
				}
				if depth == len(tc.counts) {
					deepSampled++
				}
			}
			got := Perft(p, depth)
			if got != want {
				divide, _ := PerftDivide(p, depth)
				t.Fatalf("line %d: %s\nperft(%d) = %d, want %d\ndivide: %v",
					tc.line, tc.fen, depth, got, want, divide)
			}
			nodes += got
			if depth > deepest {
				deepest = depth
			}
		}
		positions++
	}

	t.Logf("verified %d Chess960 arrangements to depth %d, %d leaf nodes", positions, deepest, nodes)
	if *perftFull {
		t.Logf("of these, %d were taken to the full depth %d; the rest stop at the node budget",
			deepSampled, len(cases[0].counts))
	} else {
		t.Logf("depths beyond the %d-node budget were skipped; use -perft-full for a deep sample", maxPerftNodes)
	}
}

// TestChess960StandardArrangementMatchesClassical is the bridge between the two
// variants. Arrangement 518 is the orthodox setup, so a position parsed in
// Chess960 mode with rooks on a1/h1 and king on e1 must reproduce the classical
// perft numbers exactly. If the generalized castling code were subtly wrong, it
// would show up here against ground truth everyone already agrees on.
func TestChess960StandardArrangementMatchesClassical(t *testing.T) {
	classical, err := ParseFEN(StartingFEN)
	if err != nil {
		t.Fatal(err)
	}
	// The same position written in Shredder notation, which forces the
	// Chess960 code paths.
	shredder, err := ParseFEN("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w HAha - 0 1")
	if err != nil {
		t.Fatal(err)
	}
	if !shredder.IsChess960() {
		t.Fatal("Shredder-notation FEN was not detected as Chess960")
	}

	for depth := 1; depth <= 5; depth++ {
		want := Perft(classical, depth)
		got := Perft(shredder, depth)
		if got != want {
			t.Errorf("depth %d: Chess960 path = %d, classical path = %d", depth, got, want)
		}
	}
}

// TestChess960CastlingEdgeCases covers the geometries that classical castling
// code cannot express at all. Each is a position where the naive assumptions —
// king on e1, rook in a corner, disjoint paths — are false.
func TestChess960CastlingEdgeCases(t *testing.T) {
	cases := []struct {
		name    string
		fen     string
		castle  string // the castling move in king-takes-rook notation
		wantOK  bool
		endFEN  string // board after castling, if legal
		comment string
	}{
		{
			// King already stands on g1, its own castling destination, so the
			// king does not move at all — only the rook does. Classical
			// encoding by king destination would produce g1g1, a null move.
			name:   "king already on its destination square",
			fen:    "4k3/8/8/8/8/8/8/5RK1 w F - 0 1",
			castle: "g1f1",
			wantOK: true,
		},
		{
			// The rook stands on the king's destination. Encoding the move as
			// the king's destination would be indistinguishable from a capture
			// of the rook.
			name:   "rook occupies the king's destination",
			fen:    "4k3/8/8/8/8/8/8/4K1R1 w G - 0 1",
			castle: "e1g1",
			wantOK: true,
		},
		{
			// King and rook swap: king b1 to c1, rook c1 to d1.
			name:   "king and rook adjacent, both move one square",
			fen:    "4k3/8/8/8/8/8/8/1KR5 w C - 0 1",
			castle: "b1c1",
			wantOK: true,
		},
		{
			// An enemy queen on a1 is blocked by the castling rook on b1.
			// Castling moves that rook away, exposing c1 — the square the king
			// is moving to. Nothing detects this before the rook lifts.
			name:    "castling rook was shielding the king's destination",
			fen:     "4k3/8/8/8/8/8/8/qR2K3 w B - 0 1",
			castle:  "e1b1",
			wantOK:  false,
			comment: "queen on a1 attacks c1 once the b1 rook steps away",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p, err := ParseFEN(tc.fen)
			if err != nil {
				t.Fatalf("ParseFEN(%q): %v", tc.fen, err)
			}

			var found Move
			for _, m := range p.LegalMoves() {
				if m.Kind() == KindCastling && m.String() == tc.castle {
					found = m
				}
			}

			if !tc.wantOK {
				if !found.IsNone() {
					t.Errorf("castling %s was generated but should be illegal (%s)", tc.castle, tc.comment)
				}
				return
			}
			if found.IsNone() {
				t.Fatalf("castling %s not generated; legal moves were %v", tc.castle, p.LegalMoves())
			}

			// The king and rook must land on the classical destinations, and
			// make/unmake must be exactly reversible despite the overlap.
			before := p.FEN()
			beforeKey := p.Key()
			p.MakeMove(found)

			us := Black
			if strings.Contains(tc.fen, " w ") {
				us = White
			}
			idx := castlingIndex(us, isKingSideCastling(found))
			if got := p.PieceAt(castlingKingTo(idx)); got != MakePiece(us, King) {
				t.Errorf("king is not on %v after castling; board:\n%s", castlingKingTo(idx), p)
			}
			if got := p.PieceAt(castlingRookTo(idx)); got != MakePiece(us, Rook) {
				t.Errorf("rook is not on %v after castling; board:\n%s", castlingRookTo(idx), p)
			}

			p.UnmakeMove()
			if got := p.FEN(); got != before {
				t.Errorf("after unmake: FEN = %q, want %q", got, before)
			}
			if p.Key() != beforeKey {
				t.Errorf("after unmake: key = %#x, want %#x", p.Key(), beforeKey)
			}
		})
	}
}

// TestChess960MoveNotation checks that castling is written the way each variant
// expects. Classical UCI wants the king's destination; Chess960 UCI wants
// king-takes-rook, because the classical form is ambiguous once a rook can
// already stand on the king's destination.
func TestChess960MoveNotation(t *testing.T) {
	classical, err := ParseFEN("r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1")
	if err != nil {
		t.Fatal(err)
	}
	if classical.IsChess960() {
		t.Fatal("KQkq FEN should not be treated as Chess960")
	}

	got := map[string]bool{}
	for _, m := range classical.LegalMoves() {
		if m.Kind() == KindCastling {
			got[classical.MoveToUCI(m)] = true
		}
	}
	for _, want := range []string{"e1g1", "e1c1"} {
		if !got[want] {
			t.Errorf("classical UCI missing %s; got %v", want, got)
		}
	}

	// The same board in Shredder notation renders king-takes-rook instead.
	c960, err := ParseFEN("r3k2r/8/8/8/8/8/8/R3K2R w HAha - 0 1")
	if err != nil {
		t.Fatal(err)
	}
	got = map[string]bool{}
	for _, m := range c960.LegalMoves() {
		if m.Kind() == KindCastling {
			got[c960.MoveToUCI(m)] = true
		}
	}
	for _, want := range []string{"e1h1", "e1a1"} {
		if !got[want] {
			t.Errorf("Chess960 UCI missing %s; got %v", want, got)
		}
	}
}

// TestParseUCIMoveResolvesCastling checks that moves arriving from a GUI are
// understood in either notation. Resolution is against the legal move list
// rather than by parsing the text, because "e1g1" can be a castle or an
// ordinary king move depending on the position.
func TestParseUCIMoveResolvesCastling(t *testing.T) {
	p, err := ParseFEN("r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1")
	if err != nil {
		t.Fatal(err)
	}

	for _, s := range []string{"e1g1", "e1c1", "e1h1", "e1a1"} {
		m, ok := p.ParseUCIMove(s)
		if !ok {
			t.Errorf("ParseUCIMove(%q) failed; both notations should be accepted", s)
			continue
		}
		if m.Kind() != KindCastling {
			t.Errorf("ParseUCIMove(%q) returned %v, want a castling move", s, m.Kind())
		}
	}

	// An ordinary king move must not be mistaken for castling.
	q, err := ParseFEN("4k3/8/8/8/8/8/8/4K3 w - - 0 1")
	if err != nil {
		t.Fatal(err)
	}
	m, ok := q.ParseUCIMove("e1f1")
	if !ok || m.Kind() != KindNormal {
		t.Errorf("ParseUCIMove(e1f1) = %v (%v), want an ordinary king move", m, m.Kind())
	}
	if _, ok := q.ParseUCIMove("e1g1"); ok {
		t.Error("ParseUCIMove accepted e1g1 with no castling rights")
	}
}

// TestChess960FENRoundTrip checks Shredder notation survives a round trip.
func TestChess960FENRoundTrip(t *testing.T) {
	fens := []string{
		"bqnb1rkr/pp3ppp/3ppn2/2p5/5P2/P2P4/NPP1P1PP/BQ1BNRKR w HFhf - 2 9",
		"2nnrbkr/p1qppppp/8/1ppb4/6PP/3PP3/PPP2P2/BQNNRBKR w HEhe - 1 9",
		"b1q1rrkb/pppppppp/3nn3/8/P7/1PPP4/4PPPP/BQNNRKRB w GE - 1 9",
	}
	for _, fen := range fens {
		p, err := ParseFEN(fen)
		if err != nil {
			t.Errorf("ParseFEN(%q): %v", fen, err)
			continue
		}
		if got := p.FEN(); got != fen {
			t.Errorf("round trip: got %q, want %q", got, fen)
		}
	}
}

// TestChess960MatchesReferenceGenerator cross-checks the fast generator against
// the naive one across Chess960 positions, exactly as the classical suite does.
// Perft would catch a wrong node count; this catches a wrong move set, and it
// covers the castling geometries perft only reaches indirectly.
func TestChess960MatchesReferenceGenerator(t *testing.T) {
	cases := loadEPD(t, "testdata/chess960_perft.epd")
	rng := newXorshift(0xC960_5EED_1234_5678)

	// Every 12th arrangement keeps the default run quick while still covering
	// 80 distinct castling geometries.
	const stride = 12
	const pliesPerPosition = 40

	positions := 0
	for i := 0; i < len(cases); i += stride {
		p, err := ParseFEN(cases[i].fen)
		if err != nil {
			t.Fatalf("line %d: %v", cases[i].line, err)
		}

		for ply := 0; ply < pliesPerPosition; ply++ {
			fast := moveStrings(p.LegalMoves())
			ref := moveStrings(p.referenceLegalMoves())
			positions++

			if strings.Join(fast, ",") != strings.Join(ref, ",") {
				t.Fatalf("move sets differ at %s\n  generator: %v\n  reference: %v\n  only in generator: %v\n  only in reference: %v",
					p.FEN(), fast, ref, difference(fast, ref), difference(ref, fast))
			}
			if len(fast) == 0 || p.HalfmoveClock() >= 100 {
				break
			}
			moves := p.LegalMoves()
			p.MakeMove(moves[rng.next()%uint64(len(moves))])
		}
	}
	t.Logf("cross-checked %d Chess960 positions against the reference generator", positions)
}
